name: Pre-Commit

on:
  pull_request:
    branches:
      - main
      - master

env:
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.48.0

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}

      - name: Setup Terraform-docs
        uses: supplypike/setup-bin@v3
        with:
          uri: https://terraform-docs.io/dl/${{ env.TERRAFORM_DOCS_VERSION }}/terraform-docs-${{ env.TERRAFORM_DOCS_VERSION }}-linux-amd64.tar.gz
          name: terraform-docs
          version: ${{ env.TERRAFORM_DOCS_VERSION }}

      - name: Setup & Run Pre-Commit
        uses: pre-commit/action@v3.0.0

      # Commit all changed files back to the repository
      - name: Commit all new changes
        uses: stefanzweifel/git-auto-commit-action@v4
